version: '3.8'

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:3.7.9
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=dental4clinic
    logging:
      options:
        max-size: 1g

