version: '3.8'

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:3.7.9
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=dental4clinic
    logging:
      options:
        max-size: 1g

  backend:
    container_name: dental4clinic-backend
    image: backend
    build:
      context: ./
      dockerfile: ./dental4clinic-backend/Dockerfile
    restart: always
    ports:
      - '3000:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      - mongo-db

